name: rokuterm
version: 0.2.2
summary: A Roku remote for terminal
description: Control your Roku or Now TV box in your terminal
confinement: strict

apps:
  rokuterm:
    command: rokuterm.py
    plugs: [network-bind]

parts:
move-src:
    plugin: dump
    source: .
    organize:
      rokuterm.py: bin/rokuterm
      wrapper: bin/wrapper
  cliftonts:
    plugin: python
    python-version: python2
    source: https://github.com/cliftonts/RokuTerm.git
    python-packages: [requests]


