name: rokuterm
version: 0.1.5
summary: A Roku remote for terminal
description: Control your Roku or Now TV box in your terminal
confinement: strict

apps:
  rokuterm:
    command: rokuterm.py
    plugs: [network-bind]

parts:
  cliftonts:
    plugin: python
    python-version: python2
    source: https://github.com/cliftonts/RokuTerm.git
    python-packages: [requests]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp rokuterm.py $SNAPCRAFT_PART_INSTALL/bin/
      chmod a+x $SNAPCRAFT_PART_INSTALL/bin/rokuterm.py

